// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATtNf4clMGoBPB5xhwor0ew2DlDVrgk5M',
    appId: '1:596861701516:web:7a45f01b17c9ff003d5aa9',
    messagingSenderId: '596861701516',
    projectId: 'expensor-8788c',
    authDomain: 'expensor-8788c.firebaseapp.com',
    databaseURL: 'https://expensor-8788c-default-rtdb.firebaseio.com',
    storageBucket: 'expensor-8788c.appspot.com',
    measurementId: 'G-86GGQ65ET8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVSE1wZ_sVON6esGHCM6hJVDP0PL5Xglw',
    appId: '1:596861701516:android:dc10722c806f2f0a3d5aa9',
    messagingSenderId: '596861701516',
    projectId: 'expensor-8788c',
    databaseURL: 'https://expensor-8788c-default-rtdb.firebaseio.com',
    storageBucket: 'expensor-8788c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo20Ttva0No9DTbOA6mF78WND9egGjqxo',
    appId: '1:596861701516:ios:c43c7a08b8017d9d3d5aa9',
    messagingSenderId: '596861701516',
    projectId: 'expensor-8788c',
    databaseURL: 'https://expensor-8788c-default-rtdb.firebaseio.com',
    storageBucket: 'expensor-8788c.appspot.com',
    iosBundleId: 'com.testing.expensor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSQBKMqpIVlN4gkhdFwrr9rKE8PK0Y-VM',
    appId: '1:800237279465:ios:2a9f15e385c931a68f3878',
    messagingSenderId: '800237279465',
    projectId: 'com-testing-flutter-auth',
    databaseURL: 'https://com-testing-flutter-auth-default-rtdb.firebaseio.com',
    storageBucket: 'com-testing-flutter-auth.appspot.com',
    iosBundleId: 'com.example.dashboardUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtv4GhBCqQ7tQ66BMCrqkxjfYH3sKQ8s0',
    appId: '1:800237279465:web:e8fe9045140b3b5a8f3878',
    messagingSenderId: '800237279465',
    projectId: 'com-testing-flutter-auth',
    authDomain: 'com-testing-flutter-auth.firebaseapp.com',
    databaseURL: 'https://com-testing-flutter-auth-default-rtdb.firebaseio.com',
    storageBucket: 'com-testing-flutter-auth.appspot.com',
    measurementId: 'G-Y25FEDL07V',
  );

}